'use client';

import { useEffect, useState } from 'react';
import {
  getAllPhotos as dbGetAllPhotos,
  savePhoto as dbSavePhoto,
  updatePhotoStatus as dbUpdatePhotoStatus,
  updatePhotoServerInfo as dbUpdatePhotoServerInfo,
  deletePhotoLocal as dbDeletePhotoLocal,
} from './indexeddb';

type LocalPhoto = Awaited<ReturnType<typeof dbGetAllPhotos>>[number];

// Single in-memory mirror of IndexedDB's photos store. Loaded from
// IndexedDB exactly ONCE, then updated in place by every mutation -
// this is what actually fixes broken/blank images, wrong-image-on-swipe,
// and retry-not-working: all three traced back to the gallery
// re-fetching ALL photos from IndexedDB on every status change, which
// hands back brand-new Blob references even for unchanged photos.
// With a stable in-memory store, a photo's Blob is set once at capture
// and never regenerated by an unrelated status tick.

let photos: LocalPhoto[] = [];
let hasLoaded = false;
const subscribers = new Set<() => void>();

function notify() {
  subscribers.forEach((cb) => cb());
}

async function ensureLoaded() {
  if (hasLoaded) return;
  photos = await dbGetAllPhotos();
  hasLoaded = true;
  notify();
}

export function usePhotos(): LocalPhoto[] {
  const [, forceRender] = useState(0);

  useEffect(() => {
    ensureLoaded();
    const cb = () => forceRender((n) => n + 1);
    subscribers.add(cb);
    return () => {
      subscribers.delete(cb);
    };
  }, []);

  return photos;
}

// Used by uploadQueue.ts, which isn't a React component and can't use
// the hook - awaits the same one-time load if it hasn't happened yet.
export async function getPhotosSnapshot(): Promise<LocalPhoto[]> {
  await ensureLoaded();
  return photos;
}

export async function addPhoto(photo: LocalPhoto) {
  await dbSavePhoto(photo);
  photos = [...photos, photo].sort((a, b) => a.shotNumber - b.shotNumber);
  notify();
}

export async function setPhotoStatus(localId: string, status: LocalPhoto['status']) {
  await dbUpdatePhotoStatus(localId, status);
  photos = photos.map((p) => (p.localId === localId ? { ...p, status } : p));
  notify();
}

export async function setPhotoServerInfo(
  localId: string,
  updates: Partial<Pick<LocalPhoto, 'status' | 'serverShotNumber' | 'fileName'>>
) {
  await dbUpdatePhotoServerInfo(localId, updates);
  photos = photos.map((p) => (p.localId === localId ? { ...p, ...updates } : p));
  notify();
}

export async function removePhoto(localId: string) {
  await dbDeletePhotoLocal(localId);
  photos = photos.filter((p) => p.localId !== localId);
  notify();
}