// Shared TypeScript types, mirroring the database schema exactly.
// Keeping these in sync with the SQL above means the frontend and
// API routes can never disagree about what shape the data is in.

export type PhotoStatus = 'uploading' | 'uploaded' | 'failed';

export interface EventSettings {
  id: 1; // always 1 - single row table
  is_enabled: boolean;
  event_start: string; // ISO timestamp string
  event_end: string;
  shot_limit: number;
  updated_at: string;
}

export interface Device {
  id: string; // uuid, generated client-side
  display_name: string;
  shots_used: number;
  created_at: string;
  last_seen_at: string;
}

export interface Photo {
  id: string; // uuid, generated by the database
  device_id: string;
  shot_number: number;
  file_name: string;
  storage_path: string | null;
  status: PhotoStatus;
  created_at: string;
  uploaded_at: string | null;
}