// The one-time screen shown to a guest the first time they open the app
// on their device. Asks for a display name, registers the device with
// the server, and saves the result locally so this screen never shows again.

'use client';

import { useState } from 'react';
import { saveDeviceInfo } from '@/lib/indexeddb';

interface RegistrationScreenProps {
  deviceId: string; // generated by the parent before this component renders
  onComplete: (displayName: string) => void; // tells the parent registration is done
}

export function RegistrationScreen({ deviceId, onComplete }: RegistrationScreenProps) {
  const [name, setName] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();

    const trimmedName = name.trim();
    if (trimmedName.length === 0) {
      setErrorMessage('Please enter your name.');
      return;
    }

    setIsSubmitting(true);
    setErrorMessage(null);

    try {
      const response = await fetch('/api/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ deviceId, displayName: trimmedName }),
      });

      if (!response.ok) {
        throw new Error('Server rejected registration');
      }

      const { device } = await response.json();

      // Only save locally AFTER the server confirms - this way, if the
      // request fails, the user sees this screen again next time instead
      // of the app thinking it's registered when the server doesn't know it.
      await saveDeviceInfo(device.id, device.display_name);

      onComplete(device.display_name);
    } catch (err) {
      console.error('Registration failed:', err);
      setErrorMessage("Couldn't connect. Please check your internet and try again.");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <div className="flex h-dvh flex-col items-center justify-center bg-black px-6 text-white">
      <h1 className="mb-2 text-2xl font-semibold">Welcome Guest!</h1>
      <p className="mb-8 text-center text-sm text-gray-400">
        Enter your name so we know whose photos are whose.
      </p>

      <form onSubmit={handleSubmit} className="w-full max-w-xs">
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Your name"
          autoFocus
          maxLength={40}
          disabled={isSubmitting}
          className="w-full rounded-lg bg-gray-800 px-4 py-3 text-center text-lg text-white placeholder-gray-500 outline-none focus:ring-2 focus:ring-white"
        />

        {errorMessage && (
          <p className="mt-3 text-center text-sm text-red-400">{errorMessage}</p>
        )}

        <button
          type="submit"
          disabled={isSubmitting}
          className="mt-4 w-full rounded-lg bg-white py-3 text-lg font-medium text-black disabled:opacity-50"
        >
          {isSubmitting ? 'Joining...' : "Let's go"}
        </button>
      </form>
    </div>
  );
}